spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: TypingProject
      auto-index-creation: true
  redis:
    usi: ${REDIS_URI}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
logging:
  level:
    org:
      springframework:
        security: DEBUG

frontend:
  url: http://localhost:5173



